//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDogsCorner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BildSpel
    {
        public int BildSpelId { get; set; }
        public string BildSpelTitel { get; set; }
        public string BildSpelBild { get; set; }
    }
}
