//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDogsCorner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrdersId { get; set; }
        public int ProduktId { get; set; }
        public Nullable<double> Pris { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
